name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools black

      - name: Lint
        run: |
          python3 -m black --check .
